name: EnderSurfer
main: com.lazini.EnderSurfer
version: 1.5
author: Lazini
commands:
    setHearts:
        usage: /setHearts <half-hearts>
        description: Sets how many half hearts should be lost when someone hits the ground after throwing an enderpearl. Default is 2.
        permission: op
        permission-message: You don't have permission to do this!
    setVelocityMultiplier:
        usage: /setVelocityMultiplier <multiplier>
        description: Set the velocity multiplier (enderpearl's velocity times the number you put here). Default is 3.
        permission: op
        permission-message: You don't have permission to do this!
    setDamageOnAir:
        usage: /setDamageOnAir <true;false>
        description: Set to true if you want the player to lose health everytime they throw an enderpearl while in the air. Default is true.
        permission: op
        permission-message: You don't have permission to do this!
