name: EnderSurfer
main: lazini.EnderSurfer
version: 1.10
author: Lazini
commands:
    endersurfer:
        usage: Gives you access to all of the other EnderSurfer commands.
        description: Gives you info about EnderSurfer
        permission: op
        permission-message: You don't have permission to do this!
        aliases: [es]
permissions:
    endersurfer.utilize:
        description: Check if a player is able to utilize EnderSurfer.
        default: true
    endersurfer.defyfalldamage:
        description: Check if a player is able to defy the fall damage he gets after throwing an ender pearl.
        default: false
    endersurfer.showparticles:
        description: Check if particles can be displayed at a player when they throw an ender pearl.
        default: true
    endersurfer.defydamageonair:
        description: Check if a player is able to defy the damage he gets while on air, after throwing an ender pearl.
        default: false
    endersurfer.elytra:
        description: Check if a player can use Ender Surfer while flying with an ender pearl. Important note! Having this off will set ender pearl usage to default, not completely cancel the event!!
        default: false
